//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 03/06/2020 20:47:53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace SavacFarma_Shared
{
    public partial class WeatherForeCast {

        public WeatherForeCast()
        {
            OnCreated();
        }

        public virtual long Id
        {
            get;
            set;
        }

        public virtual System.DateTime Date
        {
            get;
            set;
        }

        public virtual int TemperatureC
        {
            get;
            set;
        }

        public virtual string Summary
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
